app_order/urls.py
from django.urls import path
from app_order import views


app_name = 'app_order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name="cart"),
    path('remove/<pk>/', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),
]

app_payment/urls.py
from django.urls import path
from app_payment import views

app_name = 'app_payment'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
]

app_shop/urls.py
from django.urls import path
from app_shop import views

app_name = 'app_shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
]

my_ecom_project/urls.py
from django.contrib import admin
from django.urls import path, include

# to show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_shop.urls')),
    path('account/', include('app_login.urls')),
    path('shop/', include('app_order.urls')),
    path('payment/', include('app_payment.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_order/models.py
from django.db import models
from django.conf import settings

# models
from app_shop.models import Product


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="cart")
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} x {}".format(self.quantity, self.item)
    
    def get_total(self):
        total = self.item.price * self.quantity
        float_total = format(total, '0.2f')
        return float_total


class Order(models.Model):
    order_items = models.ManyToManyField(Cart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='order')
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=264, blank=True, null=True)
    orderId = models.CharField(max_length=200, blank=True, null=True)

    def get_total(self):
        total = 0
        for order_item in self.order_items.all():
            total += float(order_item.get_total())
        return total

app_order/views.py
from django.shortcuts import render, get_object_or_404, redirect

# authentications
from django.contrib.auth.decorators import login_required

# message
from django.contrib import messages

# model
from app_order.models import Cart, Order
from app_shop.models import Product


@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_item = Cart.objects.get_or_create(item=item, user=request.user, purchased=False)
    
    """ 
    -> checking this order item already exist in Order model or not for that user
    -> order = false (that means only one order for that user at a time)
    -> order = order_qs[0] as filter returns list of queryset
    """
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.order_items.filter(item=item).exists():    # if item already exist in that order
            order_item[0].quantity += 1                     # increment the item quantity
            order_item[0].save()
            messages.info(request, "This item quantity was updated")
            return redirect("app_shop:home")
        else:
            order.order_items.add(order_item[0])
            messages.info(request, "This item was added to your cart")
            return redirect('app_shop:home')
    else:
        order = Order(user=request.user)
        order.save()
        order.order_items.add(order_item[0])
        messages.info(request, "This item was added to your cart")
        return redirect("app_shop:home")


@login_required
def cart_view(request):
    carts = Cart.objects.filter(user=request.user, purchased=False)
    orders = Order.objects.filter(user=request.user, ordered=False)

    if carts.exists() and orders.exists():
        order = orders[0]
        return render(request, 'app_order/cart.html', context={'carts': carts, 'order': order})
    else:
        messages.warning(request, "You dont have any item in your cart")
        return redirect('app_shop:home')


@login_required
def remove_from_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        print('========>', order)
        if order.order_items.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            order.order_items.remove(order_item)
            order_item.delete()
            messages.warning(request, "This item was removed from your cart")
            return redirect('app_order:cart')
        else:
            messages.info(request, "This item was not in your cart")
            return redirect('app_shop:home')
    else:
        messages.info(request, "You don't have an active order")
        return redirect('app_shop:home')

    
@login_required
def increase_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.order_items.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            if order_item.quantity >= 1:
                order_item.quantity += 1
                order_item.save()
                messages.info(request, "{} quantity has been updated".format(item.name))
                return redirect('app_order:cart')
            else:
                messages.info(request, "{} quantity has been updated".format(item.name))
                return redirect('app_order:cart')
        else:
            messages.info(request, "{} is not in your cart".format(item.name))
    else:
        messages.info(request, "You don't have an active order")
        return redirect("app_shop:home")


@login_required
def decrease_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.order_items.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                messages.info(request, "{} quantity has been updated".format(item.name))
                return redirect('app_order:cart')
            else:
                order.order_items.remove(order_item)
                order_item.delete()
                messages.info(request, "{} quantity has been updated".format(item.name))
                return redirect('app_order:cart')
        else:
            messages.info(request, "{} is not in your cart".format(item.name))
    else:
        messages.info(request, "You don't have an active order")
        return redirect("app_shop:home")

templates/app_order/cart.html
{% extends 'base.html' %}
{% block body_block %}
    <div class="container my-5">`
        <div class="my-5">
            <h2>Your Cart</h2>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col" width="15%">#</th>
                    <th scope="col">Product Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col" align="right">Price</th>
                    <th scope="col">Remove</th>
                </tr>
            </thead>
            <tbody>
                {% for cart in carts %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ cart.item.name }}</td>
                        <td>
                            <a href="{% url 'app_order:decrease' pk=cart.item.pk %}" class="mr-2">
                                <span class="badge badge-light">
                                    <i class="fa fa-minus"></i>
                                </span>
                            </a>

                            {{ cart.quantity }}

                            <a href="{% url 'app_order:increase' pk=cart.item.pk %}" class="mr-2">
                                <span class="badge badge-light">
                                    <i class="fa fa-plus"></i>
                                </span>
                            </a>
                        </td>
                        <td aligh="right">&#2547; {{ cart.get_total }}</td>
                        <td><a href="{% url 'app_order:remove' pk=cart.item.pk %}" class="btn btn-danger btn-sm">Remove from Cart</a></td>
                    </tr>
                {% endfor %}
                <tr>
                    <th scope="row"></th>
                    <td colspan="3">Total</td>
                    <td align='right'>&#2547; {{ order.get_total|floatformat:2 }}</td>
                </tr>
                <tr>
                    <th scope="row"></th>
                    <td colspan="4" class="text-right">
                        <a href="{% url 'app_shop:home' %}" class="btn btn-warning mr-4">Continue Shopping</a>
                        <a href="{% url 'app_payment:checkout' %}" class="btn btn-success mr-4">Proceed To Checkout</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

{% endblock body_block %}