app_login/urls.py
from django.urls import path
from .views import sign_up, login_user, logout_user, user_profile

app_name = 'app_login'

urlpatterns = [
    path('signup', sign_up, name='signup'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('profile/', user_profile, name='profile'),
]

app_order/urls.py
from django.urls import path
from app_order import views


app_name = 'app_order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name="cart"),
    path('remove/<pk>/', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),
]

app_shop/urls.py
from django.urls import path
from app_shop import views

app_name = 'app_shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
]

my_ecom_project/urls.py
from django.contrib import admin
from django.urls import path, include

# to show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_shop.urls')),
    path('account/', include('app_login.urls')),
    path('shop/', include('app_order.urls')),
    path('payment/', include('app_payment.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="../static/css/main.css">
    <title>{% block title_block %} E-com | Eyakub {% endblock %}</title>
    <style>
        .card{
            height: 350px;
        }
        .card-product:after{
            content: "";
            display: table;
            clear: both;
            visibility: hidden;
        }
        .card-product .price-new, .card-product .price{
            margin-right: 5px;
        }
        .card-product .price-old {
            color: #999;

        }
        .card-product .img-wrap{
            border-radius: 3px 3px 0 0;
            overflow: hidden;
            position: relative;
            height: 220px;
            text-align: center;
        }
        .card-product .img-wrap img{
            max-height: 100%;
            max-width: 100%;
            object-fit: cover;
        }
        .card-product .info-wrap {
            overflow: hidden;
            padding: 15px;
            border-top: 1px solid #eee;
        }
        .card-product .action-wrap{
            padding-top: 4px;
            margin-top: 4px;
        }
        .card-product .bottom-wrap{
            padding: 15px;
            border-top: 1px solid #eee;
        }
        .card-product .title{
            margin-top: 0;
        }
    </style>
</head>
<body>
    {% include "navbar.html" %}
    <div class="container">
        <div class="messages container mt-2">
            
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{message.tags}} {% endif %}" role="alert">
                        {{ message }}
                        <button class='close' data-dismiss="alert" aria-label='close'>
                            <span aria-hidden='true'>&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
                
        </div>
        {% block body_block %}
        {% endblock %}
    </div>    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.0/jquery.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/esm/popper.min.js"></script>
</body>
</html>

templates/navbar.html
{% load cart_tag %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'app_shop:home' %}">Django E-commerce Project</a>
        <button class="navbar-toggler" type="button" 
            data-toggle="collapse" 
            data-target="#navbarNav" 
            aria-controls="navbarNav" 
            aria-expanded="false" 
            area-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            
            {% if request.user.is_authenticated %}
                
            <li class="nav-item">
                <a href="{% url 'app_order:cart' %}" class="nav-link">
                    <i class="fa fa-shopping-cart"></i> Cart
                    <span class="badge badge-light">{{ request.user |cart_total }}</span>
                </a>
             </li>
            <li class="nav-item dropdown">
                <a href="" class="nav-link dropdown-toggle" id="navbarDropdown" 
                    role="button" 
                    data-toggle="dropdown" 
                    aria-haspopup="true" 
                    aria-expanded="false">
                    <i class="fas fa-user-tie"></i>
                    {{request.user.profile.username}}
                </a>
                <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
                    <a href="{% url 'app_login:profile' %}" class="dropdown-item">Profile</a>
                    <a href="" class="dropdown-item">Order</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'app_login:logout' %}" class="dropdown-item">Logout</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="{% url 'app_login:login' %}" class="btn btn-primary">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>